name: Documentation

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Make docu
        run: julia --project=docs/ -e '
          using Pkg; 
          Pkg.develop(PackageSpec(path=pwd())); 
          Pkg.instantiate();
          Pkg.activate(".");
          Pkg.build();
          include("docs/make.jl");'
